### ISSUE TITLE
To make this code working we will need to add two environments staging and prod

### ISSUE THREAD

**Issue by ddnowicki** [BakcylProgramowania/paragon_back#23]
To make this code working we will need to add two environments staging and prod

Staging should look like:
![image](https://github.com/BakcylProgramowania/paragon_back/assets/73127307/fdcd8eae-e625-4b42-ab4e-bfcd3e458ca5)

Prod should look like:
![image](https://github.com/BakcylProgramowania/paragon_back/assets/73127307/11d51cb0-3b52-47d6-8fc6-517f20522b6b)

_Originally posted by @ddnowicki in https://github.com/BakcylProgramowania/paragon_back/issues/22#issuecomment-1874328423_

**Comment by patkaczm** [comment]
Merged under https://github.com/BakcylProgramowania/paragon_back/pull/25

**Comment by patkaczm** [comment]
Merged under https://github.com/BakcylProgramowania/paragon_back/pull/25
